# Generated by Django 3.2.4 on 2021-06-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gritapi', '0002_alter_neareathobject_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neareathobject',
            name='image',
            field=models.URLField(),
        ),
    ]
